/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "mod_ftpd"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "mod_ftpd 0.12.3"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "mod-ftpd"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.12.3"

/* Define to 1 if we are compiling with Apache 1.3.x */
/* #undef WITH_APACHE13 */

/* Define to 1 if we are compiling with Apache 2.0.x */
#define WITH_APACHE20 1


